### PR TITLE
Updated Event and Ticket contracts 

### PR DESCRIPTION
**Pull request by chin-flags**

### CODE REVIEW

**Review by cxalem — APPROVED** [review]
This looks good, the only thing that raises doubts in my mind is that the title of the NFT should contain the ID of the NFT, but I don't think this is a big problem, will think on something in next PRs

**Comment by chin-flags** [comment]
> This looks good, the only thing that raises doubts in my mind is that the title of the NFT should contain the ID of the NFT, but I don't think this is a big problem, will think on something in next PRs

What do you mean by ID of the NFT ?

**Comment by cxalem** [comment]
> > This looks good, the only thing that raises doubts in my mind is that the title of the NFT should contain the ID of the NFT, but I don't think this is a big problem, will think on something in next PRs
> 
> What do you mean by ID of the NFT ?

I mean the number, like: `Sao Paulo Web3 Festival #1` if this is the ticket with the ID number 1

Other thing is that I tried to compile the contract and I received the message:

`Warning: Contract code size is 26097 bytes and exceeds 24576 bytes (a limit introduced in Spurious Dragon). This contract may not be deployable on Mainnet. Consider enabling the optimizer (with a low "runs" value!), turning off revert strings, or using libraries.`

I think this is happening because I changed the contract from: ERC721a to ERC721URIStorage. I did this to be able to access some functions from openzeppelin that help me saving the URI for each token. Need to check this 😩

**Comment by chin-flags** [comment]
> ERC721URIStorage



> > > This looks good, the only thing that raises doubts in my mind is that the title of the NFT should contain the ID of the NFT, but I don't think this is a big problem, will think on something in next PRs
> > 
> > 
> > What do you mean by ID of the NFT ?
> 
> I mean the number, like the title of the ticket should be: `Sao Paulo Web3 Festival #1` if this is the ticket with the ID number 1
> 
> Other thing is that I tried to compile the contract and I received the message:
> 
> `Warning: Contract code size is 26097 bytes and exceeds 24576 bytes (a limit introduced in Spurious Dragon). This contract may not be deployable on Mainnet. Consider enabling the optimizer (with a low "runs" value!), turning off revert strings, or using libraries.`
> 
> I think this is happening because I changed the contract from: ERC721a to ERC721URIStorage. I did this to be able to access some functions from openzeppelin that help me saving the URI for each token. Need to check this 😩 (I'll solve this in future PRs)

Can you push your new changes to this or to a separate branch @cxalem  ?

**Comment by cxalem** [comment]
> > ERC721URIStorage
> 
> > > > This looks good, the only thing that raises doubts in my mind is that the title of the NFT should contain the ID of the NFT, but I don't think this is a big problem, will think on something in next PRs
> > > 
> > > 
> > > What do you mean by ID of the NFT ?
> > 
> > 
> > I mean the number, like the title of the ticket should be: `Sao Paulo Web3 Festival #1` if this is the ticket with the ID number 1
> > Other thing is that I tried to compile the contract and I received the message:
> > `Warning: Contract code size is 26097 bytes and exceeds 24576 bytes (a limit introduced in Spurious Dragon). This contract may not be deployable on Mainnet. Consider enabling the optimizer (with a low "runs" value!), turning off revert strings, or using libraries.`
> > I think this is happening because I changed the contract from: ERC721a to ERC721URIStorage. I did this to be able to access some functions from openzeppelin that help me saving the URI for each token. Need to check this 😩 (I'll solve this in future PRs)
> 
> Can you push your new changes to this or to a separate branch @cxalem ?

Here it is: https://github.com/Consensys/eventsea/pull/18

**Pull request merged**
